stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - C:\Users\evilk\Downloads\Compressed\Main_Training\train
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw
    outs:
      - data/processed

  # visualize_processed_vs_raw:
  #   cmd: python src/visualization/compare_processed_vs_raw.py
  #   deps:
  #     - src/visualization/compare_processed_vs_raw.py
  #     - data/raw/train
  #     - data/processed/train
  #   outs:
  #     - reports/figures/processed_vs_raw # <--- always run this stage

  augment_features:
    cmd: python src/features/features_augmentation.py
    deps:
      - src/features/features_augmentation.py
      - data/processed/train
      - data/processed/val
    outs:
      - data/features/train
      - data/features/val

  # visualize_processed_vs_features:
  #   cmd: python src/visualization/compare_processed_vs_features.py
  #   deps:
  #     - src/visualization/compare_processed_vs_features.py
  #     - data/processed/train
  #     - data/features/train
  #   outs:
  #     - reports/figures/processed_vs_features

  clinical_model:
    cmd: python src/models/clinical_model.py
    deps:
      - src/models/clinical_model.py
      - data/features/train
      - data/features/val
    outs:
      - models/clinical/clinical_model.pt
      - models/clinical/clinical_model_lite.pt

  research_training:
    cmd: python src/models/research_model.py
    deps:
      - src/models/research_model.py
      - data/features/
    outs:
      - models/research_model/
