stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - C:\Users\evilk\Downloads\Compressed\Main_Training\train
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw
    outs:
      - data/Processed

  visualize:
    cmd: python src/visualization/compare_processed_vs_raw.py
    deps:
      - src/visualization/compare_processed_vs_raw.py
      - data/raw/train
      - data/Processed/train
    outs:
      - reports/figures/processed_vs_raw

  # baseline_train:
  #   cmd: python src/models/baseline_model.py
  #   deps:
  #     - src/models/baseline_model.py
  #     - data/processed/Main_Training/train
  #   outs:
  #     - models/baseline_3d_unet.h5

  # evaluate:
  #   cmd: python src/models/baseline_model_evaluation.py
  #   deps:
  #     - models/baseline_3d_unet.h5
  #     - data/processed/Main_Training/train
  #   outs:
  #     - metrics/evaluation.json
  #     - metrics/evaluation.csv

  # data_augmentation:
  #   cmd: python src/features/features_augmentation.py
  #   deps:
  #     - src/features/features_augmentation.py
  #     - data/processed/Main_Training/train/image
  #     - data/processed/Main_Training/train/mark
  #     - data/processed/Main_Training/val/image
  #   outs:
  #     - data/features/Main_Training/train/image_aug
  #     - data/features/Main_Training/train/mask_aug

  # build_clinical_model:
  #   cmd: python src/models/build_clinical_model.py
  #   deps:
  #     - src/models/build_clinical_model.py
  #   outs:
  #     - models/clinical_unet_2d.h5

  # build_research_model:
  #   cmd: python src/models/build_research_model.py
  #   outs:
  #     - models/research_attention_unet_3d.h5
  #   deps:
  #     - src/models/build_research_model.py
